alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - engine: PG
    name: super-agi-main
    num_nodes: 1
    size: basic-xs
    version: "12"
ingress:
  rules:
    - component:
        name: chatdevagi-backend
      match:
        path:
          prefix: /api
name: chatdevagi
services:
  - dockerfile_path: DockerfileRedis
    github: 
      branch: main
      deploy_on_push: true
      repo: ebit.tpb.vn/gitlab/PhucHC/chatdev2.0.git 
    internal_ports: 
    - 6379
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: /
    name: chatdevagi-redis
  - dockerfile_path: Dockerfile
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: chatdevagi-redis:6379
      - key: DB_URL
        scope: RUN_TIME
        value: ${super-agi-main.DATABASE_URL}
    github:
      branch: main
      deploy_on_push: true
      repo: ebit.tpb.vn/gitlab/PhucHC/chatdev2.0.git 
    http_port: 8001
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: /app/entrypoint.sh
    source_dir: /
    name: chatdevagi-backend
  - dockerfile_path: ./gui/DockerfileProd
    github:
      branch: main
      deploy_on_push: true
      repo: ebit.tpb.vn/gitlab/PhucHC/chatdev2.0.git 
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: ./gui
    name: chatdevagi-gui
workers:
  - dockerfile_path: Dockerfile
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: chatdevagi-redis:6379
      - key: DB_URL
        scope: RUN_TIME
        value: ${super-agi-main.DATABASE_URL}
    github:
      branch: main
      deploy_on_push: true
      repo: ebit.tpb.vn/gitlab/PhucHC/chatdev2.0.git
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: celery -A chatdevagi.worker worker --beat --loglevel=info
    source_dir: /
    name: chatdevagi-celery
  
